#include "src/game/envfx_snow.h"

const GeoLayout yoshi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 200, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 2, -4, -3),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, yoshi_000_offset_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 100, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 222, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, -146, 49, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(2, geo_switch_anim_state),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, NULL),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(1, 51, 55, 97, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 74, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 69, 0, 0, NULL),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(1, 51, 55, -97, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 74, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 69, 0, 0, NULL),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(1, -1, 27, 95, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 100, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 95, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(1, -89, -62, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(1, -1, 27, -95, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 100, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 95, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, yoshi_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, yoshi_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
